name: whisper-v3
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - opencv
  - numpy
  - pillow
  - ffmpeg
  - pip:
    - torch
    - transformers>=4.35.0
    - datasets[audio]
    - accelerate
    - soundfile
    - librosa
    - moviepy 