name: face-masker
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - opencv
  - numpy
  - pillow
  - pip:
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - python-multipart==0.0.6
    - jinja2==3.1.2
    - python-socketio==5.10.0
    - websockets==12.0
    - ultralytics==8.3.168
    - huggingface_hub==0.20.3
    - torch>=2.0.0
    - torchvision>=0.15.0
    - aiofiles==23.2.1
    - python-dotenv==1.0.0
    - pydantic==2.5.0
    - redis==5.0.1 